# https://github.com/docker/awesome-compose/

services:
  jvstar_backend:
    build: ./
    ports:
      - 12345:8080
    environment:
      - POSTGRES_DB=jvstar
      - POSTGRES_PASSWORD=jvstar
      - POSTGRES_USER=jvstar
    networks:
      - spring-postgres
    depends_on:
      jvstar_postgres:
        condition: service_healthy

  jvstar_postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - jvstar-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=jvstar
      - POSTGRES_PASSWORD=jvstar
      - POSTGRES_USER=jvstar
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jvstar-data:
networks:
  spring-postgres:
